import { env } from '@/config/env';

/**
 * Agora token management.
 *
 * SECURITY NOTE: In production, tokens should be generated by a Supabase Edge Function
 * or secure backend, NOT in the client app. The current implementation uses a
 * development token from env for local testing only.
 *
 * Production flow:
 * 1. Client requests token from Edge Function
 * 2. Edge Function validates the user has permission to join the channel
 * 3. Edge Function generates token using Agora App Certificate (server-side only)
 * 4. Token is returned to client with expiration
 */

export type AgoraTokenResult = {
  token: string;
  uid: number;
  channelName: string;
  expiresAt: number;
};

/**
 * Get Agora token for joining a channel.
 * In production, this should call a Supabase Edge Function.
 */
export async function getAgoraToken(
  channelName: string,
  uid: number
): Promise<AgoraTokenResult> {
  // For development: use the token from env
  // In production: call Edge Function
  if (env.hasCallCredentials) {
    return {
      token: env.AGORA_TOKEN,
      uid,
      channelName,
      expiresAt: Date.now() + 3600_000, // 1 hour
    };
  }

  // Fallback: try to call Edge Function
  try {
    const response = await fetch(
      `${env.SUPABASE_URL}/functions/v1/agora-token`,
      {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${env.SUPABASE_PUBLISHABLE_KEY}`,
        },
        body: JSON.stringify({ channelName, uid }),
      }
    );

    if (!response.ok) {
      throw new Error('Failed to get Agora token');
    }

    return await response.json();
  } catch {
    throw new Error('Unable to connect to call service. Please try again.');
  }
}

/**
 * Check if token is expired or about to expire.
 */
export function isTokenExpired(expiresAt: number): boolean {
  return Date.now() >= expiresAt - 60_000; // Refresh 1 min before expiry
}
